### ISSUE TITLE
Non-GLSL pattern "inputs" - static images and video

### ISSUE THREAD

**Issue by zbanks** [zbanks/radiance#18]
It'd be cool to have patterns defined by e.g. a static PNG image or a webcam video stream.

**Comment by gdkar** [comment]
Not quite webcam-style / realtime input, exactly, but I'm gonna go ahead and suggest working off something like libmpv for reasonable video decode/playback/rate modification/seeking/not having to reinvent the wheel entirely.

a la:
https://github.com/mpv-player/mpv-examples/tree/master/libmpv/qt_opengl

or similar.

( This should be incredibly straightforward --- and I'll take a stab at actually getting it done, like, tomorrow or something? )

**Comment by zbanks** [comment]
Great, make sure you work on the qt branch and not master.

**Comment by ervanalb** [comment]
Great, make sure you work on the modelview branch and not qt

**Comment by zbanks** [comment]
Note: static images & GIF are supported now with `ImageNode` on the modelview branch. Leaving this issue open to handle video inputs (webcam, .mp4)

**Comment by zbanks** [comment]
Merged branch `mpv` into `master`
