### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by zbanks** [zbanks/radiance#19]
Run from the command line with minimal interaction.

**Comment by zbanks** [comment]
Latest commit has the closest thing to this that we've ever had -- rendering patterns to images.

We should still consider a headless mode that renders to a monitor live, possibly with some simple controls.

**Comment by ervanalb** [comment]
Once `outputs_are_nodes_too` gets merged in, you can instantiate a `ScreenOutputNode` from the CLI, which achieves this

**Comment by zbanks** [comment]
I'm finally happy with this after merging #54
