### ISSUE TITLE
Add MIDI controller support to the qt branch

### ISSUE THREAD

**Issue by zbanks** [zbanks/radiance#23]
Regression

**Comment by zbanks** [comment]
In progress; there's now ``MidiDevice`` which bridges RtMidi. Questionable API; and also uses a ``QTimer`` to poll the underlying rtmidi object which seems kind of off... not sure how to correctly incorporate the rtmidi callback API with threading...

**Comment by zbanks** [comment]
@gdkar helpfully re-wrote it to use callbacks; needs to be hooked up to qml objects

**Comment by ervanalb** [comment]
Needs to be ported over to modelview branch

**Comment by ervanalb** [comment]
First pass at MIDI is done, you can instantiate a `MidiController` in QML and connect the raw MIDI signals coming from it to the View's attached property `Controls`. Example mapping is in `ControllerMapping.qml` for the DJ Control Air.
