### ISSUE TITLE
Lux Output

### ISSUE THREAD

**Issue by zbanks** [zbanks/radiance#26]
Most of the way there... not sure if rendering works. Need a way to specify the polygon path for devices.

**Comment by ervanalb** [comment]
Now this needs to be ported over to modelview branch

**Comment by zbanks** [comment]
@ervanalb can you at least stub out how you expect this to work?

**Comment by ervanalb** [comment]
`OutputImageSequence` is a good starting point.

**Comment by ervanalb** [comment]
lol your traceback copypasta referenced every ticket

**Comment by ervanalb** [comment]
`outputs_are_nodes_too` is a substantial refactor out outputs, once that gets merged in I will implement a `DataOutputNode` which dumps frames into RAM and hands them to you periodically. Then I'll re-assign this ticket to @zbanks who will handle the actual lux stuff.

**Comment by ervanalb** [comment]
Handing this off to @zbanks now that STRBON is in

**Comment by ervanalb** [comment]
Closing this ticket as lux support can be implemented using the more generic `LightOutputNode`
