### ISSUE TITLE
devil does not load nyancat

### ISSUE THREAD

**Issue by ervanalb** [zbanks/radiance#31]
Probably it doesn't load any images / gifs. It thinks it loads correctly though.

Says: `Successfully loaded image "../resources/images/nyancat.gif"`
but that tile shows up as a black square.

Devil / ILUT version:
Version: 1.8.0-2

**Comment by zbanks** [comment]
Worked for me, I was using Devil version 1.7.8-10

**Comment by ervanalb** [comment]
Fixed, there were three issues:
https://github.com/zbanks/radiance/commit/803dbe5709fdc4751be3a3d4117d5cec797451e4#diff-7a2cdba86b379d728cdff53904e7286fR31
https://github.com/zbanks/radiance/commit/803dbe5709fdc4751be3a3d4117d5cec797451e4#diff-7a2cdba86b379d728cdff53904e7286fR110
https://github.com/zbanks/radiance/commit/803dbe5709fdc4751be3a3d4117d5cec797451e4#diff-7a2cdba86b379d728cdff53904e7286fR178

**Comment by mboorstin** [comment]
@ervanalb thanks for fixing my shit; rush and stuff at work ate my life for a month :-(
