### ISSUE TITLE
Atomically alter graph

### ISSUE THREAD

**Issue by ervanalb** [zbanks/radiance#37]
Using `addVideoNode`, `removeVideoNode`, `addEdge`, `removeEdge` are cool and all, but they cause somewhat glitchy behavior and patterns can be dropped from the rendering if it happens between when a node is disconnected and when it is reconnected.

These should probably be replaced with a `changeGraph(removeNodes, addNodes, removeEdges, addEdges)` method that atomically alters the graph.

**Comment by zbanks** [comment]
I think you actually what `changeGraph(actions)`, where `actions` is a list of things like `["addEdge", 1, 2, 0]`.

This is nice because serialized state is useful for undo too.

**Comment by zbanks** [comment]
An issue with `changeGraph(removeNodes, addNodes, removeEdges, addEdges)` is that there might be ordering issues between the 4 lists of operations?

**Comment by ervanalb** [comment]
A better way to do this is to have any graph-altering operation happen on a back buffer. Things like `addVideoNode()` `edges()` and `selectedConnectedComponents()` operate on this buffer, but renderers use the front buffer. Calling `flush()` atomically pushes through changes from the back buffer to the front buffer, and causes `graphChanged()` signals to be emitted.
