### ISSUE TITLE
ImageNode should use timings from GIF instead of 10 FPS

### ISSUE THREAD

**Issue by zbanks** [zbanks/radiance#39]
Right now `ImageNode` just plays back the animated image at 10 FPS, regardless of the timings specified in the image file. The data is loaded into the `m_frameDelays` list; it just needs to be read and cycled through appropriately.

**Comment by ervanalb** [comment]
I think there should be two sliders on GIFs, one for speed (fwd+reverse) and one scrub bar for position within the gif (that scrolls with speed or manually)

**Comment by ervanalb** [comment]
This has been fixed for a while now...
