### ISSUE TITLE
Store EffectNode metadata in/alongside the effect GLSL

### ISSUE THREAD

**Issue by zbanks** [zbanks/radiance#41]
Right now it's super easy to add an effect: you just have to write a single file `resources/effects/$name.0.glsl`. (For images, you just stick the image in `resources/images/`)

`NodeRegistry` currently holds the logic to scan the directory for these files and grab the name. We should also extract:
- Number of inputs (this is currently hardcoded in NodeRegistry)
- Description (usually the first line(s) of the `effect.0.glsl` file

The bulk of the logic should also be moved into `EffectNode`/`ImageNode` as static methods.

Ideally, I want to keep the metadata inside the GLSL file itself, I think that's much easier to keep track of. We could also try putting all the layers (e.g. `effect.0.glsl` + `effect.1.glsl`) in the same file too...

**Comment by gdkar** [comment]
I, uh, have written ~ this, if you're interested in using that as a
starting point; i didn't push that up 'cause it was faulting out, but that
was true even without my changes.

**Comment by gdkar** [comment]
caveat, the thing i did doesn't pull anything into the registry: it just
parses at effect load time. refactoring to actually have an "effect
prototype object" or whatever would probably be good.

**Comment by zbanks** [comment]
Cool. If you want you could just shove it in here, and we can refactor it later:
https://github.com/zbanks/radiance/blob/modelview/src/NodeRegistry.cpp#L106-L127

**Comment by gdkar** [comment]
okay. yeah, the changes i'd made were just in EffectNode, not the registry,
but duplicating that over for now should be quick; gimme maybe an hour or
two.

**Comment by gdkar** [comment]
So I have in-effect specification / single file effects merged in and
mostly working; rardiance still segfaults on start for me unless I run
under gdb ( but that's true even without my changes ) so I'm not completely
sold that I should push this up yet.

**Comment by zbanks** [comment]
It looks like you missed some changes I made to patterns (mostly fixing alpha issues from when we switched to premul'd alpha, but also missing `crt` and maybe others)
This diff shows it pretty well:

https://github.com/zbanks/radiance/compare/ce2185a2d1...7e2277fddd

**Comment by zbanks** [comment]
Also it fails an assert for me (backtrace included)
```
ASSERT: "QThread::currentThread() == thread()" in file /home/zbanks/radiance_mv/src/VideoNode.cpp, line 25

Thread 3 "openGLWorkerCon" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe3fff700 (LWP 14901)]
0x00007ffff4d93428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff4d93428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff4d9502a in __GI_abort () at abort.c:89
#2  0x00007ffff5a5fcd1 in qt_message_fatal (context=..., message=<synthetic pointer>) at global/qlogging.cpp:1690
#3  QMessageLogger::fatal (this=this@entry=0x7fffe3ffe430, msg=msg@entry=0x7ffff5d54418 "ASSERT: \"%s\" in file %s, line %d") at global/qlogging.cpp:796
#4  0x00007ffff5a5b03e in qt_assert (assertion=assertion@entry=0x498dc8 "QThread::currentThread() == thread()", file=file@entry=0x498d98 "/home/zbanks/radiance_mv/src/VideoNode.cpp", line=line@entry=25)
    at global/qglobal.cpp:3049
#5  0x000000000045577d in VideoNode::setInputCount (this=0x2bcf040, value=1) at /home/zbanks/radiance_mv/src/VideoNode.cpp:25
#6  0x000000000048a877 in VideoNode::qt_static_metacall (_o=_o@entry=0x2bcf040, _c=_c@entry=QMetaObject::WriteProperty, _id=_id@entry=0, _a=_a@entry=0x7fffe3ffe5e0)
    at /home/zbanks/radiance_mv/build/moc_VideoNode.cpp:236
#7  0x000000000048c09b in VideoNode::qt_metacall (this=this@entry=0x2bcf040, _c=_c@entry=QMetaObject::WriteProperty, _id=0, _a=_a@entry=0x7fffe3ffe5e0) at /home/zbanks/radiance_mv/build/moc_VideoNode.cpp:281
#8  0x000000000048c0c5 in EffectNode::qt_metacall (this=0x2bcf040, _c=QMetaObject::WriteProperty, _id=<optimized out>, _a=0x7fffe3ffe5e0) at /home/zbanks/radiance_mv/build/moc_EffectNode.cpp:378
#9  0x00007ffff5c65890 in QMetaProperty::write (this=this@entry=0x7fffe3ffe930, object=0x2bcf040, value=...) at kernel/qmetaobject.cpp:3128
#10 0x000000000045aeec in EffectNodeOpenGLWorker::loadProgram (this=this@entry=0xbb9e00, name=...) at /home/zbanks/radiance_mv/src/EffectNode.cpp:357
#11 0x000000000045b8ef in EffectNodeOpenGLWorker::initialize (this=0xbb9e00) at /home/zbanks/radiance_mv/src/EffectNode.cpp:240
#12 0x0000000000487bc5 in EffectNodeOpenGLWorker::qt_static_metacall (_o=0xbb9e00, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at /home/zbanks/radiance_mv/build/moc_EffectNode.cpp:95
#13 0x00007ffff5c845c9 in QObject::event (this=0xbb9e00, e=<optimized out>) at kernel/qobject.cpp:1246
#14 0x00007ffff5c56faa in doNotify (event=<optimized out>, receiver=<optimized out>) at kernel/qcoreapplication.cpp:1093
#15 QCoreApplication::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at kernel/qcoreapplication.cpp:1079
#16 0x00007ffff5c57108 in QCoreApplication::notifyInternal2 (receiver=0xbb9e00, event=event@entry=0x2df9040) at kernel/qcoreapplication.cpp:1018
#17 0x00007ffff5c598eb in QCoreApplication::sendEvent (event=0x2df9040, receiver=<optimized out>) at kernel/qcoreapplication.h:233
#18 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x833a00) at kernel/qcoreapplication.cpp:1678
#19 0x00007ffff5c59d58 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1532
#20 0x00007ffff5cacc93 in postEventSourceDispatch (s=0x7fffdc0012d0) at kernel/qeventdispatcher_glib.cpp:276
#21 0x00007ffff15e2197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff15e23f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff15e249c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff5cac29f in QEventDispatcherGlib::processEvents (this=0x7fffdc0008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#25 0x00007ffff5c5513a in QEventLoop::exec (this=this@entry=0x7fffe3ffee40, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#26 0x00007ffff5a729a4 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:515
#27 0x00007ffff5a77659 in QThreadPrivate::start (arg=0x830b70) at thread/qthread_unix.cpp:368
#28 0x00007ffff65926ba in start_thread (arg=0x7fffe3fff700) at pthread_create.c:333
#29 0x00007ffff4e653dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

It looks like you shouldn't set the `inputCount` of the `EffectNode` in the `EffectNodeOpenGLWorker` thread. (It used to be set by the main thread). 

I wonder if we can relax this assert in `VideoNode` to allow out-of-thread setting of `inputCount`? @ervanalb  thoughts?

```
void VideoNode::setInputCount(int value) {
    Q_ASSERT(QThread::currentThread() == thread());

    if(value != m_inputCount) {
        {
            QMutexLocker locker(&m_stateLock);
            m_inputCount = value;
        }
        emit inputCountChanged(value);
    }
}
```

Otherwise, this is pretty cool.

**Comment by gdkar** [comment]
I'm... confused that it was asserting there, mostly 'cause i didn't see
that happening?

Also the locking around that is garbage. ( It's a race condition to even
/check/ m_inputCount outside of the lock, if the lock was needed at all. )
but.... that's an issue for later.

I was setting from the OpenGLWorker, since when I wrote that code ( pre
rebasing ) it wasn't being set in the registry; if it /is/ being set in the
registry, the set in the worker can probably just be entirely elided.

**Comment by zbanks** [comment]
@gdkar did this.
