### ISSUE TITLE
Effect previews flicker if more than 1 output is active

### ISSUE THREAD

**Issue by zbanks** [zbanks/radiance#42]

**Comment by ervanalb** [comment]
I can't repro this, can you be more specific?

**Comment by ervanalb** [comment]
I've seen this but its very hard to repro. Will see if it still exists in `outputs_are_nodes_too` which substantially changes the way outputs work.

**Comment by ervanalb** [comment]
I'm going to close this since I think it is fixed with the recent refactors. Feel free to re-open if it comes back.
