### ISSUE TITLE
ImageNode should have one input

### ISSUE THREAD

**Issue by ervanalb** [zbanks/radiance#43]
It should composite itself onto its input (possibly with an opacity slider)

**Comment by zbanks** [comment]
That's an implementation detail, but we probably will still want to subclass it differently for static images, animated gifs/video clips, and live video because they can have very different controls on the UI side.

**Comment by gdkar** [comment]
Fair; yeah, I didn't say this was an argument I'd *win* necessarily. :P

I guess, in my mind, there're two major approaches to doing the source <->
effect separation. Notably:

Effects can specify input buffers to be *whatever*, but then everything is
an "effect" ( this is the direct shadertoy approach )

vs.

there're separate source and shader entities; shaders can specify what
/ports/ they present ( and possibly request default attachment to
particular sources ) but feeding source data in is "actually just an
effect-effect connection"

( the third state of "but also effects can specify that they take input
resources that aren't Inputs" is also possible, and maybe worthwhile. It
strikes me as sort of awkward and hacked-on in the presence of either of
the two approaches listed above, but that doesn't mean it's not a valid
thing necessarily. )

....

But, yeah, also that's definitely not an exhaustive list; ymmv.

**Comment by ervanalb** [comment]
Closing this cause it does now (not perfect but acceptable)
