### ISSUE TITLE
Output does not work (Binary on Ubuntu 16.04.3 LTS - LXDE)

### ISSUE THREAD

**Issue by itf** [zbanks/radiance#48]
I tried running Radiance.AppDir on my lubuntu laptop. 

The UI works fine; however, show output just displays a black screen and takes over my windows manager. And "save to disk" just saves 500x500px  black frames.

![000000](https://user-images.githubusercontent.com/6120993/33160009-ea6ff4a2-cfe6-11e7-9a2c-8b76e58d72ce.png)

I haven't tried compiling the project from scratch yet, though.

**Comment by ervanalb** [comment]
Did you select an output by clicking a tile and hitting "Enter" ? That should make screen output work.

To make Image output work, find the drop-down box at the top of the screen that says "Screen" and change it to "ImageSequence", then select a tile and hit enter.

The UI for outputs is still in the works.

**Comment by itf** [comment]
First changing the output to screen and then pressing enter works! Pressing enter and then changing the output to screen does not work. I was doing it out of order.

solved
