### ISSUE TITLE
Get rid of the ugly widgets at the top of the screen

### ISSUE THREAD

**Issue by ervanalb** [zbanks/radiance#52]
Replace it with what is apparently known as a "hamburger menu"

**Comment by Firescar96** [comment]
idk, I like them, they make the app look more interesting, like more stuff is going on
the waveforms in particular are useful at a glance to check i have my sound output setup correctly

**Comment by ervanalb** [comment]
yeah the waveform and stuff are definitely staying, I want to get rid of the buttons and comboboxes

**Comment by ervanalb** [comment]
(also this is done in #71)
