### ISSUE TITLE
Output Node properties are non persistent

### ISSUE THREAD

**Issue by Firescar96** [zbanks/radiance#69]
Properties of nodes appear to be lost on restart.
Current behavior
For example: using the kinetics-backend branch I can create a Color Kinetics Strip Output and set the host, width, etc. Upon closing and reopening radiance the node is still there in the gui, but it no longer transmits to the ColorKinetics device. I have to recreate the output.

Desired behavior
The parameters passed on instantiation of the node are persistent and are re-deserialized to create a new output node whenever radiance restarts.

**Comment by ervanalb** [comment]
To get loading and saving to work, you need to override `serialize` and `deserialize` in your node's class. These functions convert your node to and from JSON so it can be written to save files. The default methods don't save any information other than the node type. See `MovieNode` for an example of how to add parameters to your node's JSON representation.

**Comment by Firescar96** [comment]
resolved, thx
